version: '3'
services:
  bld:
    build: build-image 
    volumes:
      - type: volume
        source: artifacts
        target: /boxfuse-sample-java-war-hello/target/hello-1.0.war

  prod:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: artifacts
        target: /usr/local/tomcat/webapps/hello-1.0.war
volumes: 
  artifacts: