version: '3'
services:
  bld:
    build: build-image 
    volumes:
      - type: volume
        source: artifacts
        target: /boxfuse-sample-java-war-hello/target

  prod:
    image: tomcat:8.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: artifacts
        target: /usr/local/tomcat/webapps
volumes: 
  artifacts: