version: '3'
services:
  bld:
    build: build-image 
    volumes:
      - type: volume
        source: artifacts
        target: /boxfuse-sample-java-war-hello/target/

  prod:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes_from:
      - bld
    command: [cp /boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/local/tomcat/webapps/; catalina.sh run]
volumes: 
  artifacts: